const subCategories = [
    { category: 1, name: "Food & Beverage" },
    { category: 1, name: "Transportation" },
    { category: 1, name: "Rentals" },
    { category: 1, name: "Water Bill" },
    { category: 1, name: "Phone Bill" },
    { category: 1, name: "Electricity Bill" },
    { category: 1, name: "Gas Bill" },
    { category: 1, name: "Television Bill" },
    { category: 1, name: "Internet Bill" },
    { category: 1, name: "Other Utility Bills" },
    { category: 2, name: "Home Maintenance" },
    { category: 2, name: "Vehicle Maintenance" },
    { category: 2, name: "Medical Check Up" },
    { category: 2, name: "Insurances" },
    { category: 2, name: "Education" },
    { category: 2, name: "Houseware" },
    { category: 2, name: "Personal Items" },
    { category: 2, name: "Pets" },
    { category: 2, name: "Home Services" },
    { category: 3, name: "Fitness" },
    { category: 3, name: "Makeup" },
    { category: 2, name: "Other Expense" },
    { category: 3, name: "Gifts & Donations" },
    { category: 3, name: "Streaming Service" },
    { category: 3, name: "Fun Money" },
    { category: 4, name: "Investment" },
    { category: 4, name: "Loan" },
    { category: 4, name: "Repayment" },
    { category: 4, name: "Pay Interest" },
    { category: 7, name: "Outgoing Transfer" },
    { category: 5, name: "Debt Collection" },
    { category: 5, name: "Debt" },
    { category: 5, name: "Collect Interest" },
    { category: 6, name: "Other Income" },
    { category: 6, name: "Salary" },
    { category: 8, name: "Incoming Transfer" },
];